spring.application.name=ecommerce-Gateway-Server
server.port=8080
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.value}

#Gateway server properties
spring.cloud.gateway.server.webflux.routes[0].id=orders
spring.cloud.gateway.server.webflux.routes[0].uri=lb://order-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/ecommerce/orders/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1

#Products and Categories
spring.cloud.gateway.server.webflux.routes[1].id=products
spring.cloud.gateway.server.webflux.routes[1].uri=lb://product-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/ecommerce/products/**,/ecommerce/categories/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1

#Auth service
spring.cloud.gateway.server.webflux.routes[2].id=auth
spring.cloud.gateway.server.webflux.routes[2].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/ecommerce/auth/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=1
