spring.application.name=order-service
spring.config.import=configserver:http://localhost:8888
#spring.cloud.discovery.client.simple.instances.product-service[0].uri=http://localhost:8082
#spring.cloud.discovery.client.simple.instances.product-service[1].uri=http://localhost:8086

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#usage of Ip address
eureka.instance.prefer-ip-address=true
# unique name
eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.value}

#Resilience4j properties
resilience4j.retry.instances.testRetry.maxAttempts=3
resilience4j.retry.instances.testRetry.waitDuration=2s
resilience4j.retry.instances.testRetry.enableExponentialBackoff=true
resilience4j.retry.instances.testRetry.exponentialBackoffMultiplier=2

#circuit Breaker
resilience4j.circuitbreaker.instances.testCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.testCircuitBreaker.minimumNumberOfCalls=4
resilience4j.circuitbreaker.instances.testCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.testCircuitBreaker.waitDurationInOpenState=60s
resilience4j.circuitbreaker.instances.testCircuitBreaker.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.testCircuitBreaker.automaticTransitionFromOpenToHalfOpenEnabled=true
