spring.application.name=product-service
spring.config.import=configserver:http://localhost:8888
management.endpoints.web.exposure.include=refresh
#eureka running
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#usage of Ip address
eureka.instance.prefer-ip-address=true
# unique name
eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.value}

#Tracing
management.tracing.sampling.probability=1.0
management.tracing.export.zipkin.endpoint=http://localhost:9411/api/v2/spans
